import { InvoiceDtl } from "../interfaces/Invoice.interface";
import { NameCommon } from "../interfaces/namecommon.interface";

export class InvoiceDtlDto implements InvoiceDtl{
  invDTLId: number=0;
  branchId: number=0;
  invId: number=0;
  invType: number=0;
  year: number=0;
  storeId: number=0;
  itemId: number=0;
  itemCode: number=0;
  unitId: number=0;
  unitCode?: number | undefined;
  unitName?: string | undefined;
  expireDate: Date=new Date();
  backType: number=0;
  backId: number=0;
  backYear: number=0;
  itemPrice: number=0;
  itemCurValue: number=0;
  itemQty: number=0;
  guaranteeDate: Date=new Date();
  totalItemCredit: number=0;
  totalItemDebit: number=0;
  totalBaseItemCredit: number=0;
  totalBaseItemDebit: number=0;
  discType: number=0;
  discValue: number=0;
  discAmtCredit: number=0;
  discAmtDebit: number=0;
  discBaseCredit: number=0;
  discBaseDebit: number=0;
  isPosted: boolean=false;
  notes: string='';
  userNAME: string='';

  timeSTAMP: Date=new Date();
  accountId: string='';
  itemCostDebit: number=0;
  itemCostCredit: number=0;
  sellAccId: number=0;
  costAccId: number=0;
  discAccId: number=0;
  taxAccId: string='';
  taxDebit: number=0;
  taxBaseDebit: number=0;
  itemCost: number=0;
  taxBaseCredit: number=0;
  taxCredit: number=0;
  backSellAccId: string='';
  backBuyAccId: string='';
  itemStoreCurValue: number=0;
  itemCur: number=0;
  totalItemSbaseCredit: number=0;
  totalItemSbaseDebit: number=0;
  itemDefCur: number=0;
  transSeq: number=0;
  empAccId: string='';
  empAmt: number=0;
  empBaseAmt: number=0;
  empRatio: number=0;
  empCurValue: number=0;
  itemCostBase: number=0;
  delivId: number=0;
  delYear: number=0;
  delTransSeq: number=0;
  inStoreId: number=0;
  nonDescribe: string='';
  date: Date=new Date();
  itemName: string='';
  vatAMT: number=0;
  vatDebitAccId: string='';
  vatCreditAccId: string='';
  addAMT: number=0;
  delSheepRemain: boolean=false;
  discAmt: number=0;
  itemUnitId: number=0;
  price: number=0;
  qty: number=0;
  qtyPlate: number=0;
  sheepRemainder: number=0;
  tag: number=0;
  vatPrice: number=0;
  vatTotal: number=0;
  itemType: number=0;
  invIsCancel: boolean=false;
  companyId: number=0;
  invIsActive: boolean=false;
  isDeleted: boolean=false;
  createdBy: number=0;
  createdOn: Date=new Date();
  lastUpdatedBy: number=0;
  lastUpdatedOn: Date=new Date();
  qtyOrder: number=0;
  qtyRemain: number=0;
  qtyTransfer: number=0;
  qtyExp: number=0;
  item?: NameCommon | undefined;
  unit?: NameCommon | undefined;

}
