import { NameCommon } from "./namecommon.interface";

export interface Invoice {
    invId:number
	branchId:number,
	invCode:string,
	invtype:number,
	year:number,
	invRef:string,
	invDate:Date,
	sellerId:number,


	payCash:boolean,
	payCheck:boolean,
	payLater:boolean,
	invBaseAmt:number,
	discPerc:number,
	isPosted:boolean,
	storeId:number,
	storeCode:number,
	storeName:string,
	discAmt:number,
	invSubCost:number,
	notes:string,
	permitId:number,
	permitType:number,
	orderType:number,
	orderId:number,
	customerId:number,
	saleTax:number,
	saleTax2:number,
	person:string,
	invSeq:number,
	invRefDate:Date,
	invCurValue:number,
	invCur:number,
	invDisc:number,
	permitYear:number,
	bankId:number,
	cardNo:string,
	accountId:string,
	expireDate:Date,
	cardType:number,
	amt:number,
	curValue:number,
	baseAmt:number,
	bankSource:string,
	payVisa:number,
	areaId:number,
	qutId:number,
	qutType:number,
	typeId:number,
	pAYED:number,
	getComm:number,
	deliveries:string,
	returnOnDelivery:number,
	goodInvId:number,
	setSaleRet:number,
	retOnDelyear:number,
	tableId:string,
	visitNo:number,
	reqNo:number,
	surgId:number,
	debitType:number,
	insurTrans:number,
	contNo:number,
	insurancePerc:number,
	cmpAccId:number,
	salesId:number,
	salesCode:number,
	salesName:string,
	fromBranches:number,
	invIsWait:boolean,
	invIsCancel:boolean,
	periodId:number,
	branchCompId:number,
	subSeq:number,
	payTypeId:number,
	costCenterId:number,
	cashDeskId:number,
	invStatus:number,
	orderSeq:number,
	insurance:number,
	insurPerc:number,
	service:number,
	servicePerc:number,
	tax:number,
	taxPerc:number,
	discount:number,
	discountPerc:number,
	pointId:number,
	delivery:number,
	deliveryPerc:number,
	invMachine:string,
	pcIdentification:string,
	orderLocSeq:number,
	orederDaySeq:number,
	invPayType:number,
	deliveryInvoice:boolean,
	deliveryDate:Date,
	delLocSeq:number,
	invPhoneNo:string,
	isPrepare:boolean,
	isTransPost:boolean,
	priceCat:number,
	siteId:number,
	locAddressInvoice:string,
	anotherInvId:number,
	casherDiscount:number,
	discountSell:number,
	customerName:string,
	branchTransId:string,
	companyId:number,
	usedPoints:number,
	mealPoints:number,
	invoiceIsActive:boolean,
	isDeleted:boolean,
	createdBy:number,
	createdOn:Date,
	lastUpdatedBy:number,
	lastUpdatedOn:Date,
	invoiceDtl:InvoiceDtl[],
	payment:InvoiceCashDetails[

	],
}
export interface InvoiceCashDetails {
	id: number;
	invoiceId: number;
	accountId: number;
	accountNo: string;
	accountName: string;
	currencyId: number;
	currencyExchange?: number;
	debit?: number;
	amount?: number;
	costCenterId?: number;
	costCenterCode?: number;
	costCenterName?: '';
	notes: string;
	debitDefaultCurrency?: number;
	amountDefaultCurrency?: number;
	account?: NameCommon;
	costCenter?: NameCommon;
	currency?: NameCommon;
  }
  
export interface InvoiceDtl {
	invDTLId:number,
	branchId:number,
	invId:number,
	invType:number,
	year:number,
	storeId:number,
	itemId:number,
	itemCode:number,
	unitId:number,
	unitCode?:number,
	unitName?:string,
	expireDate:Date,
	backType:number,
	backId:number,
	backYear:number,
	itemPrice:number,
	itemCurValue:number,
	itemQty:number,
    guaranteeDate:Date,
	totalItemCredit:number,
	totalItemDebit:number,
	totalBaseItemCredit:number,
	totalBaseItemDebit:number,
	discType:number,
	discValue:number,
	discAmtCredit:number,
	discAmtDebit:number,
	discBaseCredit:number,
	discBaseDebit:number,
	isPosted:boolean,
	notes:string,
	userNAME:string,
	timeSTAMP:Date,
	accountId:string,
	itemCostDebit:number,
	itemCostCredit:number,
	sellAccId:number,
	costAccId:number,
	discAccId:number,
	taxAccId:string,
	taxDebit:number,
	taxBaseDebit:number,
	itemCost:number,
	taxBaseCredit:number,
	taxCredit:number,
	backSellAccId:string,
	backBuyAccId:string,
	itemStoreCurValue:number,
	itemCur:number,
	totalItemSbaseCredit:number,
	totalItemSbaseDebit:number,
	itemDefCur:number,
	transSeq:number,
	empAccId:string,
	empAmt:number,
	empBaseAmt:number,
	empRatio:number,
	empCurValue:number,
	itemCostBase:number,
	delivId:number,
	delYear:number,
	delTransSeq:number,
	inStoreId:number,
	nonDescribe:string,
	date:Date,
	itemName:string,
	vatAMT:number,
	vatDebitAccId:string,
	vatCreditAccId:string,
	addAMT:number,
	delSheepRemain:boolean,
	discAmt:number,
	itemUnitId:number,
	price:number,
	qty:number,
	qtyPlate:number,
	sheepRemainder:number,
	tag:number,
	vatPrice:number,
	vatTotal:number,
	itemType:number,
	invIsCancel:boolean,
	companyId:number,
	invIsActive:boolean,
	isDeleted:boolean,
	createdBy:number,
	createdOn:Date,
	lastUpdatedBy:number,
	lastUpdatedOn:Date,
	qtyOrder:number,
	qtyRemain:number,
	qtyTransfer:number,
	qtyExp:number,
	item?: NameCommon;
	unit?: NameCommon;
}